import { OptionType } from "@/app/types/types";
export const options: OptionType[] = [
  { key: 1, value: "australia", label: "オーストラリア" },
  { key: 2, value: "canada", label: "カナダ" },
  { key: 3, value: "new-zealand", label: "ニュージーランド" },
  { key: 4, value: "south-korea", label: "韓国" },
  { key: 5, value: "france", label: "フランス" },
  { key: 6, value: "taiwan", label: "台湾" },
  { key: 7, value: "hungary", label: "ハンガリー" },
  { key: 8, value: "united-kingdom", label: "イギリス" },
  { key: 9, value: "spain", label: "スペイン" },
  { key: 10, value: "argentina", label: "アルゼンチン" },
  { key: 11, value: "chile", label: "チリ" },
  { key: 12, value: "iceland", label: "アイスランド" },
  { key: 13, value: "czech-republic", label: "チェコ" },
  { key: 14, value: "lithuania", label: "リトアニア" },
  { key: 15, value: "sweden", label: "スウェーデン" },
  { key: 16, value: "estonia", label: "エストニア" },
  { key: 17, value: "netherlands", label: "オランダ" },
  { key: 18, value: "uruguay", label: "ウルグアイ" },
  { key: 19, value: "finland", label: "フィンランド" },
  { key: 20, value: "latvia", label: "ラトビア" },
  { key: 21, value: "ireland", label: "アイルランド" },
  { key: 22, value: "denmark", label: "デンマーク" },
  { key: 23, value: "germany", label: "ドイツ" },
  { key: 24, value: "norway", label: "ノルウェー" },
  { key: 25, value: "poland", label: "ポーランド" },
  { key: 26, value: "portugal", label: "ポルトガル" },
  { key: 27, value: "slovakia", label: "スロバキア" },
  { key: 28, value: "austria", label: "オーストリア" },
  { key: 29, value: "hong-kong", label: "香港" },
];
